import { ProblemSeed } from '../seed.ts';

export const dpProblems: ProblemSeed[] = [
  // Easy (15)
  {
    title: 'Climbing Stairs',
    slug: 'climbing-stairs',
    description:
      'You are climbing a staircase. Each time you can climb 1 or 2 steps. Count how many distinct ways to reach the top.',
    difficulty: 'EASY',
    topic: 'Dynamic Programming',
    examples: [{ input: 'n = 2', output: '2', explanation: '1+1, 2' }],
    constraints: ['1 <= n <= 45'],
    testCases: [
      { input: 'n = 2', expectedOutput: '2' },
      { input: 'n = 3', expectedOutput: '3' },
      { input: 'n = 10', expectedOutput: '89', isHidden: true },
    ],
  },
  {
    title: 'Min Cost Climbing Stairs',
    slug: 'min-cost-climbing-stairs',
    description:
      'Given cost[] where cost[i] is cost of i-th step, return min cost to reach top (can start at step 0 or 1).',
    difficulty: 'EASY',
    topic: 'Dynamic Programming',
    examples: [{ input: 'cost = [10,15,20]', output: '15' }],
    constraints: ['2 <= cost.length <= 1000', '0 <= cost[i] <= 1000'],
    testCases: [
      { input: 'cost = [10,15,20]', expectedOutput: '15' },
      { input: 'cost = [1,100,1,1,1,100,1,1,100,1]', expectedOutput: '6' },
      { input: 'cost = [0,0,0]', expectedOutput: '0', isHidden: true },
    ],
  },
  {
    title: 'Fibonacci Number',
    slug: 'fibonacci-number',
    description: 'Return the n-th Fibonacci number (F0 = 0, F1 = 1).',
    difficulty: 'EASY',
    topic: 'Dynamic Programming',
    examples: [{ input: 'n = 4', output: '3' }],
    constraints: ['0 <= n <= 30'],
    testCases: [
      { input: 'n = 0', expectedOutput: '0' },
      { input: 'n = 4', expectedOutput: '3' },
      { input: 'n = 10', expectedOutput: '55', isHidden: true },
    ],
  },
  {
    title: 'Tribonacci Number',
    slug: 'tribonacci-number',
    description: 'Return the n-th Tribonacci number (T0 = 0, T1 = 1, T2 = 1).',
    difficulty: 'EASY',
    topic: 'Dynamic Programming',
    examples: [{ input: 'n = 4', output: '4' }],
    constraints: ['0 <= n <= 37'],
    testCases: [
      { input: 'n = 0', expectedOutput: '0' },
      { input: 'n = 4', expectedOutput: '4' },
      { input: 'n = 10', expectedOutput: '149', isHidden: true },
    ],
  },
  {
    title: 'House Robber',
    slug: 'house-robber',
    description:
      'Given non-negative nums representing money at each house, return max amount without robbing adjacent houses.',
    difficulty: 'EASY',
    topic: 'Dynamic Programming',
    examples: [{ input: 'nums = [1,2,3,1]', output: '4' }],
    constraints: ['1 <= nums.length <= 100', '0 <= nums[i] <= 1000'],
    testCases: [
      { input: 'nums = [1,2,3,1]', expectedOutput: '4' },
      { input: 'nums = [2,7,9,3,1]', expectedOutput: '12' },
      { input: 'nums = [0,0,0]', expectedOutput: '0', isHidden: true },
    ],
  },
  {
    title: 'Counting Bits',
    slug: 'counting-bits',
    description:
      'Given n, return an array ans where ans[i] is number of 1s in binary representation of i for 0..n.',
    difficulty: 'EASY',
    topic: 'Dynamic Programming',
    examples: [{ input: 'n = 2', output: '[0,1,1]' }],
    constraints: ['0 <= n <= 10^5'],
    testCases: [
      { input: 'n = 2', expectedOutput: '[0,1,1]' },
      { input: 'n = 5', expectedOutput: '[0,1,1,2,1,2]' },
      { input: 'n = 0', expectedOutput: '[0]', isHidden: true },
    ],
  },
  {
    title: 'Decode Ways (Easy Variant)',
    slug: 'decode-ways-easy',
    description:
      'A message is encoded with A=1..Z=26. Given string of digits, count the number of ways to decode (no leading zeros).',
    difficulty: 'EASY',
    topic: 'Dynamic Programming',
    examples: [{ input: 's = "12"', output: '2' }],
    constraints: ['1 <= s.length <= 30', 's contains only digits'],
    testCases: [
      { input: 's = "12"', expectedOutput: '2' },
      { input: 's = "226"', expectedOutput: '3' },
      { input: 's = "10"', expectedOutput: '1', isHidden: true },
    ],
  },
  {
    title: 'Maximum Sum Without Adjacent',
    slug: 'max-sum-without-adjacent',
    description: 'Given array of integers, return maximum sum of non-adjacent elements.',
    difficulty: 'EASY',
    topic: 'Dynamic Programming',
    examples: [{ input: 'nums = [3,2,5,10,7]', output: '15' }],
    constraints: ['1 <= nums.length <= 1000', '-10^4 <= nums[i] <= 10^4'],
    testCases: [
      { input: 'nums = [3,2,5,10,7]', expectedOutput: '15' },
      { input: 'nums = [2,1,1,2]', expectedOutput: '4' },
      { input: 'nums = [-1,5,4,-3]', expectedOutput: '9', isHidden: true },
    ],
  },
  {
    title: 'Frog Jump Basics',
    slug: 'frog-jump-basics',
    description: 'A frog can jump 1..k steps. Given n and k, how many ways to reach the top?',
    difficulty: 'EASY',
    topic: 'Dynamic Programming',
    examples: [{ input: 'n = 3, k = 2', output: '3' }],
    constraints: ['1 <= n <= 30', '1 <= k <= n'],
    testCases: [
      { input: 'n = 3, k = 2', expectedOutput: '3' },
      { input: 'n = 4, k = 3', expectedOutput: '8' },
      { input: 'n = 10, k = 2', expectedOutput: '89', isHidden: true },
    ],
  },
  {
    title: 'Coin Change Count Ways (Easy)',
    slug: 'coin-change-count-ways-easy',
    description:
      'Given coins and amount, count the number of combinations to make amount (order does not matter).',
    difficulty: 'EASY',
    topic: 'Dynamic Programming',
    examples: [{ input: 'coins = [1,2,5], amount = 5', output: '4' }],
    constraints: ['1 <= coins.length <= 30', '0 <= amount <= 1000'],
    testCases: [
      { input: 'coins = [1,2,5], amount = 5', expectedOutput: '4' },
      { input: 'coins = [2], amount = 3', expectedOutput: '0' },
      { input: 'coins = [1], amount = 0', expectedOutput: '1', isHidden: true },
    ],
  },
  {
    title: 'Unique Paths',
    slug: 'unique-paths',
    description:
      'Count number of paths from top-left to bottom-right in m x n grid moving only right or down.',
    difficulty: 'EASY',
    topic: 'Dynamic Programming',
    examples: [{ input: 'm = 3, n = 2', output: '3' }],
    constraints: ['1 <= m, n <= 100'],
    testCases: [
      { input: 'm = 3, n = 2', expectedOutput: '3' },
      { input: 'm = 7, n = 3', expectedOutput: '28' },
      { input: 'm = 1, n = 1', expectedOutput: '1', isHidden: true },
    ],
  },
  {
    title: 'Grid Traveler',
    slug: 'grid-traveler',
    description:
      'Count distinct ways to travel a grid from (0,0) to (m,n) moving only right or down.',
    difficulty: 'EASY',
    topic: 'Dynamic Programming',
    examples: [{ input: 'm = 2, n = 3', output: '3' }],
    constraints: ['1 <= m, n <= 50'],
    testCases: [
      { input: 'm = 2, n = 3', expectedOutput: '3' },
      { input: 'm = 3, n = 3', expectedOutput: '6' },
      { input: 'm = 10, n = 1', expectedOutput: '1', isHidden: true },
    ],
  },
  {
    title: 'Perfect Squares (Easy)',
    slug: 'perfect-squares-easy',
    description: 'Given n, return least number of perfect square numbers that sum to n.',
    difficulty: 'EASY',
    topic: 'Dynamic Programming',
    examples: [{ input: 'n = 12', output: '3' }],
    constraints: ['1 <= n <= 10^4'],
    testCases: [
      { input: 'n = 12', expectedOutput: '3' },
      { input: 'n = 13', expectedOutput: '2' },
      { input: 'n = 1', expectedOutput: '1', isHidden: true },
    ],
  },
  {
    title: 'Integer Break (Easy)',
    slug: 'integer-break-easy',
    description:
      'Break n into sum of at least two positive integers to maximize product; return max product.',
    difficulty: 'EASY',
    topic: 'Dynamic Programming',
    examples: [{ input: 'n = 2', output: '1' }],
    constraints: ['2 <= n <= 58'],
    testCases: [
      { input: 'n = 2', expectedOutput: '1' },
      { input: 'n = 10', expectedOutput: '36' },
      { input: 'n = 8', expectedOutput: '18', isHidden: true },
    ],
  },
  {
    title: 'Staircase Variations',
    slug: 'staircase-variations',
    description:
      'Count ways to climb stairs when allowed steps are from a given set (e.g., {1,3,5}).',
    difficulty: 'EASY',
    topic: 'Dynamic Programming',
    examples: [{ input: 'n = 5, steps = [1,3,5]', output: '5' }],
    constraints: ['1 <= n <= 30', '1 <= steps.length <= 10'],
    testCases: [
      { input: 'n = 5, steps = [1,3,5]', expectedOutput: '5' },
      { input: 'n = 4, steps = [1,2]', expectedOutput: '5' },
      { input: 'n = 20, steps = [1,2]', expectedOutput: '10946', isHidden: true },
    ],
  },

  // Medium (15)
  {
    title: 'Coin Change',
    slug: 'coin-change',
    description:
      'Given coins and amount, return fewest number of coins to make amount or -1 if impossible.',
    difficulty: 'MEDIUM',
    topic: 'Dynamic Programming',
    examples: [{ input: 'coins = [1,2,5], amount = 11', output: '3' }],
    constraints: ['1 <= coins.length <= 12', '0 <= amount <= 10^4'],
    testCases: [
      { input: 'coins = [1,2,5], amount = 11', expectedOutput: '3' },
      { input: 'coins = [2], amount = 3', expectedOutput: '-1' },
      { input: 'coins = [1], amount = 0', expectedOutput: '0', isHidden: true },
    ],
  },
  {
    title: 'Longest Increasing Subsequence',
    slug: 'longest-increasing-subsequence',
    description:
      'Return length of the longest strictly increasing subsequence in an integer array.',
    difficulty: 'MEDIUM',
    topic: 'Dynamic Programming',
    examples: [{ input: 'nums = [10,9,2,5,3,7,101,18]', output: '4' }],
    constraints: ['1 <= nums.length <= 2500', '-10^4 <= nums[i] <= 10^4'],
    testCases: [
      { input: 'nums = [10,9,2,5,3,7,101,18]', expectedOutput: '4' },
      { input: 'nums = [0,1,0,3,2,3]', expectedOutput: '4' },
      { input: 'nums = [7,7,7,7,7,7,7]', expectedOutput: '1', isHidden: true },
    ],
  },
  {
    title: 'Longest Common Subsequence',
    slug: 'longest-common-subsequence',
    description: 'Given two strings, return length of longest common subsequence.',
    difficulty: 'MEDIUM',
    topic: 'Dynamic Programming',
    examples: [{ input: 'text1 = "abcde", text2 = "ace"', output: '3' }],
    constraints: ['0 <= text1.length, text2.length <= 1000'],
    testCases: [
      { input: 'text1 = "abcde", text2 = "ace"', expectedOutput: '3' },
      { input: 'text1 = "abc", text2 = "abc"', expectedOutput: '3' },
      { input: 'text1 = "abc", text2 = "def"', expectedOutput: '0', isHidden: true },
    ],
  },
  {
    title: 'House Robber II',
    slug: 'house-robber-ii',
    description:
      'Houses are in a circle. Maximize robbery without adjacent houses (first and last adjacent).',
    difficulty: 'MEDIUM',
    topic: 'Dynamic Programming',
    examples: [{ input: 'nums = [2,3,2]', output: '3' }],
    constraints: ['1 <= nums.length <= 100', '0 <= nums[i] <= 1000'],
    testCases: [
      { input: 'nums = [2,3,2]', expectedOutput: '3' },
      { input: 'nums = [1,2,3,1]', expectedOutput: '4' },
      { input: 'nums = [0,0,0]', expectedOutput: '0', isHidden: true },
    ],
  },
  {
    title: 'Partition Equal Subset Sum',
    slug: 'partition-equal-subset-sum',
    description: 'Determine if array can be partitioned into two subsets with equal sum.',
    difficulty: 'MEDIUM',
    topic: 'Dynamic Programming',
    examples: [{ input: 'nums = [1,5,11,5]', output: 'true' }],
    constraints: ['1 <= nums.length <= 200', '1 <= nums[i] <= 100'],
    testCases: [
      { input: 'nums = [1,5,11,5]', expectedOutput: 'true' },
      { input: 'nums = [1,2,3,5]', expectedOutput: 'false' },
      { input: 'nums = [100,100]', expectedOutput: 'true', isHidden: true },
    ],
  },
  {
    title: 'Target Sum',
    slug: 'target-sum',
    description:
      'Given array and target, assign + or - to make sum equal target. Return number of ways.',
    difficulty: 'MEDIUM',
    topic: 'Dynamic Programming',
    examples: [{ input: 'nums = [1,1,1,1,1], target = 3', output: '5' }],
    constraints: ['1 <= nums.length <= 20', '0 <= nums[i] <= 1000'],
    testCases: [
      { input: 'nums = [1,1,1,1,1], target = 3', expectedOutput: '5' },
      { input: 'nums = [1], target = 2', expectedOutput: '0' },
      { input: 'nums = [0,0,0,0,0], target = 0', expectedOutput: '32', isHidden: true },
    ],
  },
  {
    title: 'Word Break',
    slug: 'word-break',
    description:
      'Given string s and dictionary words, determine if s can be segmented into sequence of dictionary words.',
    difficulty: 'MEDIUM',
    topic: 'Dynamic Programming',
    examples: [{ input: 's = "leetcode", wordDict = ["leet","code"]', output: 'true' }],
    constraints: ['1 <= s.length <= 300', '1 <= wordDict.length <= 1000'],
    testCases: [
      { input: 's = "leetcode", wordDict = ["leet","code"]', expectedOutput: 'true' },
      { input: 's = "applepenapple", wordDict = ["apple","pen"]', expectedOutput: 'true' },
      {
        input: 's = "catsandog", wordDict = ["cats","dog","sand","and","cat"]',
        expectedOutput: 'false',
        isHidden: true,
      },
    ],
  },
  {
    title: 'Decode Ways',
    slug: 'decode-ways',
    description: 'Count number of ways to decode a digit string using A=1..Z=26.',
    difficulty: 'MEDIUM',
    topic: 'Dynamic Programming',
    examples: [{ input: 's = "226"', output: '3' }],
    constraints: ['1 <= s.length <= 1000'],
    testCases: [
      { input: 's = "226"', expectedOutput: '3' },
      { input: 's = "06"', expectedOutput: '0' },
      { input: 's = "11106"', expectedOutput: '2', isHidden: true },
    ],
  },
  {
    title: 'Unique Paths II',
    slug: 'unique-paths-ii',
    description: 'Unique paths with obstacles in grid represented by 1s. Return number of paths.',
    difficulty: 'MEDIUM',
    topic: 'Dynamic Programming',
    examples: [{ input: 'grid = [[0,0,0],[0,1,0],[0,0,0]]', output: '2' }],
    constraints: ['m == grid.length', 'n == grid[0].length', '1 <= m,n <= 100'],
    testCases: [
      { input: 'grid = [[0,0,0],[0,1,0],[0,0,0]]', expectedOutput: '2' },
      { input: 'grid = [[0,1],[0,0]]', expectedOutput: '1' },
      { input: 'grid = [[1]]', expectedOutput: '0', isHidden: true },
    ],
  },
  {
    title: 'Maximum Product Subarray',
    slug: 'maximum-product-subarray',
    description: 'Find contiguous subarray that has largest product and return the product.',
    difficulty: 'MEDIUM',
    topic: 'Dynamic Programming',
    examples: [{ input: 'nums = [2,3,-2,4]', output: '6' }],
    constraints: ['1 <= nums.length <= 2 * 10^4', '-10 <= nums[i] <= 10'],
    testCases: [
      { input: 'nums = [2,3,-2,4]', expectedOutput: '6' },
      { input: 'nums = [-2,0,-1]', expectedOutput: '0' },
      { input: 'nums = [-1,-2,-9,-6]', expectedOutput: '108', isHidden: true },
    ],
  },
  {
    title: 'Jump Game',
    slug: 'jump-game',
    description:
      'Given nums where nums[i] is max jump length at i, return true if can reach last index.',
    difficulty: 'MEDIUM',
    topic: 'Dynamic Programming',
    examples: [{ input: 'nums = [2,3,1,1,4]', output: 'true' }],
    constraints: ['1 <= nums.length <= 10^4', '0 <= nums[i] <= 10^5'],
    testCases: [
      { input: 'nums = [2,3,1,1,4]', expectedOutput: 'true' },
      { input: 'nums = [3,2,1,0,4]', expectedOutput: 'false' },
      { input: 'nums = [0]', expectedOutput: 'true', isHidden: true },
    ],
  },
  {
    title: 'Jump Game II',
    slug: 'jump-game-ii',
    description: 'Return minimum number of jumps to reach last index.',
    difficulty: 'MEDIUM',
    topic: 'Dynamic Programming',
    examples: [{ input: 'nums = [2,3,1,1,4]', output: '2' }],
    constraints: ['1 <= nums.length <= 10^4'],
    testCases: [
      { input: 'nums = [2,3,1,1,4]', expectedOutput: '2' },
      { input: 'nums = [2,3,0,1,4]', expectedOutput: '2' },
      { input: 'nums = [1,1,1,1]', expectedOutput: '3', isHidden: true },
    ],
  },

  // Continuing Medium - total 15
  {
    title: 'Edit Distance',
    slug: 'edit-distance',
    description:
      'Given two strings word1 and word2, return min number of operations to convert word1 to word2 (insert, delete, replace).',
    difficulty: 'MEDIUM',
    topic: 'Dynamic Programming',
    examples: [{ input: 'word1 = "horse", word2 = "ros"', output: '3' }],
    constraints: ['0 <= word1.length, word2.length <= 500'],
    testCases: [
      { input: 'word1 = "horse", word2 = "ros"', expectedOutput: '3' },
      { input: 'word1 = "intention", word2 = "execution"', expectedOutput: '5' },
      { input: 'word1 = "", word2 = "a"', expectedOutput: '1', isHidden: true },
    ],
  },
  {
    title: 'Minimum Path Sum',
    slug: 'minimum-path-sum',
    description:
      'Given grid of non-negative numbers, find path from top-left to bottom-right minimizing sum.',
    difficulty: 'MEDIUM',
    topic: 'Dynamic Programming',
    examples: [{ input: 'grid = [[1,3,1],[1,5,1],[4,2,1]]', output: '7' }],
    constraints: ['m == grid.length', 'n == grid[0].length', '1 <= m,n <= 200'],
    testCases: [
      { input: 'grid = [[1,3,1],[1,5,1],[4,2,1]]', expectedOutput: '7' },
      { input: 'grid = [[1]]', expectedOutput: '1' },
      { input: 'grid = [[5,9],[4,1]]', expectedOutput: '10', isHidden: true },
    ],
  },
  {
    title: 'Knapsack 0/1',
    slug: 'knapsack-0-1',
    description:
      'Given items with weights and values and capacity W, maximize total value without exceeding W.',
    difficulty: 'MEDIUM',
    topic: 'Dynamic Programming',
    examples: [{ input: 'weights = [1,3,4], values = [15,20,30], W = 4', output: '35' }],
    constraints: ['1 <= n <= 200', '1 <= W <= 1000'],
    testCases: [
      { input: 'weights = [1,3,4], values = [15,20,30], W = 4', expectedOutput: '35' },
      { input: 'weights = [2,3,4], values = [3,4,5], W = 5', expectedOutput: '7' },
      { input: 'weights = [1], values = [100], W = 0', expectedOutput: '0', isHidden: true },
    ],
  },

  // Hard (10)
  {
    title: 'Regular Expression Matching',
    slug: 'regular-expression-matching',
    description: 'Implement regex matching with support for "." and "*".',
    difficulty: 'HARD',
    topic: 'Dynamic Programming',
    examples: [{ input: 's = "aa", p = "a*"', output: 'true' }],
    constraints: ['0 <= s.length, p.length <= 20'],
    testCases: [
      { input: 's = "aa", p = "a"', expectedOutput: 'false' },
      { input: 's = "aa", p = "a*"', expectedOutput: 'true' },
      { input: 's = "ab", p = ".*"', expectedOutput: 'true', isHidden: true },
    ],
  },
  {
    title: 'Burst Balloons',
    slug: 'burst-balloons',
    description:
      'Given nums of balloons with coins, choose bursting order to maximize coins earned where burst i yields nums[left]*nums[i]*nums[right].',
    difficulty: 'HARD',
    topic: 'Dynamic Programming',
    examples: [{ input: 'nums = [3,1,5,8]', output: '167' }],
    constraints: ['1 <= nums.length <= 500', '0 <= nums[i] <= 100'],
    testCases: [
      { input: 'nums = [3,1,5,8]', expectedOutput: '167' },
      { input: 'nums = [1,5]', expectedOutput: '10' },
      { input: 'nums = [7]', expectedOutput: '7', isHidden: true },
    ],
  },
  {
    title: 'Distinct Subsequences',
    slug: 'distinct-subsequences',
    description: 'Count number of distinct ways to form T from S by deleting characters.',
    difficulty: 'HARD',
    topic: 'Dynamic Programming',
    examples: [{ input: 's = "rabbbit", t = "rabbit"', output: '3' }],
    constraints: ['0 <= s.length, t.length <= 1000'],
    testCases: [
      { input: 's = "rabbbit", t = "rabbit"', expectedOutput: '3' },
      { input: 's = "babgbag", t = "bag"', expectedOutput: '5' },
      { input: 's = "aaaaa", t = "aa"', expectedOutput: '10', isHidden: true },
    ],
  },
  {
    title: 'Palindrome Partitioning II',
    slug: 'palindrome-partitioning-ii',
    description:
      'Given string s, partition into minimum cuts so that every substring is a palindrome.',
    difficulty: 'HARD',
    topic: 'Dynamic Programming',
    examples: [{ input: 's = "aab"', output: '1' }],
    constraints: ['1 <= s.length <= 2000'],
    testCases: [
      { input: 's = "aab"', expectedOutput: '1' },
      { input: 's = "a"', expectedOutput: '0' },
      { input: 's = "cbbbcc"', expectedOutput: '2', isHidden: true },
    ],
  },
  {
    title: 'Interleaving String',
    slug: 'interleaving-string',
    description: 'Given s1, s2, s3, determine whether s3 is formed by interleaving s1 and s2.',
    difficulty: 'HARD',
    topic: 'Dynamic Programming',
    examples: [{ input: 's1 = "aabcc", s2 = "dbbca", s3 = "aadbbcbcac"', output: 'true' }],
    constraints: ['0 <= s1.length, s2.length <= 100'],
    testCases: [
      { input: 's1 = "aabcc", s2 = "dbbca", s3 = "aadbbcbcac"', expectedOutput: 'true' },
      { input: 's1 = "a", s2 = "", s3 = "c"', expectedOutput: 'false' },
      { input: 's1 = "", s2 = "", s3 = ""', expectedOutput: 'true', isHidden: true },
    ],
  },
  {
    title: 'Scramble String',
    slug: 'scramble-string',
    description: 'Determine if s2 is a scramble of s1 (binary partition and swap operations).',
    difficulty: 'HARD',
    topic: 'Dynamic Programming',
    examples: [{ input: 's1 = "great", s2 = "rgeat"', output: 'true' }],
    constraints: ['1 <= s1.length == s2.length <= 30'],
    testCases: [
      { input: 's1 = "great", s2 = "rgeat"', expectedOutput: 'true' },
      { input: 's1 = "abcde", s2 = "caebd"', expectedOutput: 'false' },
      { input: 's1 = "a", s2 = "a"', expectedOutput: 'true', isHidden: true },
    ],
  },
  {
    title: 'Wildcard Matching',
    slug: 'wildcard-matching',
    description:
      'Implement wildcard matching with ? and * where ? matches single char and * matches any sequence.',
    difficulty: 'HARD',
    topic: 'Dynamic Programming',
    examples: [{ input: 's = "aa", p = "*"', output: 'true' }],
    constraints: ['0 <= s.length, p.length <= 2000'],
    testCases: [
      { input: 's = "aa", p = "a"', expectedOutput: 'false' },
      { input: 's = "aa", p = "*"', expectedOutput: 'true' },
      { input: 's = "cb", p = "?a"', expectedOutput: 'false', isHidden: true },
    ],
  },
  {
    title: 'DP on Trees Problem',
    slug: 'dp-on-trees-problem',
    description:
      'Given a tree with values on nodes, compute maximum sum of non-adjacent nodes (tree DP).',
    difficulty: 'HARD',
    topic: 'Dynamic Programming',
    examples: [{ input: 'edges = [[1,2],[1,3]], vals = [3,2,3]', output: '6' }],
    constraints: ['1 <= n <= 10^5'],
    testCases: [
      { input: 'edges = [[1,2],[1,3]], vals = [3,2,3]', expectedOutput: '6' },
      { input: 'edges = [[1,2]], vals = [1,2]', expectedOutput: '2' },
      { input: 'edges = [], vals = [5]', expectedOutput: '5', isHidden: true },
    ],
  },
  {
    title: 'DP with Bitmasking Problem',
    slug: 'dp-with-bitmasking',
    description: 'Solve TSP-style shortest Hamiltonian path using DP over bitmasks (small n).',
    difficulty: 'HARD',
    topic: 'Dynamic Programming',
    examples: [{ input: 'dist matrix for 3 nodes', output: 'minimal tour cost' }],
    constraints: ['1 <= n <= 16'],
    testCases: [
      { input: 'n = 3, dist = [[0,1,15],[1,0,2],[15,2,0]]', expectedOutput: '4' },
      { input: 'n = 2, dist = [[0,5],[5,0]]', expectedOutput: '10' },
      { input: 'n = 1, dist = [[0]]', expectedOutput: '0', isHidden: true },
    ],
  },
  {
    title: 'Advanced State Compression DP',
    slug: 'advanced-state-compression-dp',
    description:
      'A placeholder for problems requiring compressing multiple state dimensions into bitmasks and DP transitions; typical tasks include assignment with constraints.',
    difficulty: 'HARD',
    topic: 'Dynamic Programming',
    examples: [{ input: 'example NP-hard sized small n', output: 'optimal value' }],
    constraints: ['n small (<= 16) typically'],
    testCases: [
      { input: 'n = 3, matrix = [[0,1,2],[1,0,3],[2,3,0]]', expectedOutput: '3' },
      { input: 'n = 2, matrix = [[0,1],[1,0]]', expectedOutput: '1' },
      { input: 'n = 4, matrix sample', expectedOutput: '6', isHidden: true },
    ],
  },
];
