import type { ProblemSeed } from '../seed.ts';

export const expandedProblemSeeds: ProblemSeed[] = [
  // Linked Lists - Easy
  {
    title: 'Reverse Linked List',
    description: 'Reverse a singly linked list and return the head of the reversed list.',
    difficulty: 'EASY',
    topic: 'Linked Lists',
    examples: [{ input: 'head = [1,2,3,4,5]', output: '[5,4,3,2,1]' }],
    constraints: ['0 <= number of nodes <= 5000', '-5000 <= Node.val <= 5000'],
    sampleInput: 'head = [1,2,3,4,5]',
    sampleOutput: '[5,4,3,2,1]',
    testCases: [
      { input: 'head = [1,2,3,4,5]', expectedOutput: '[5,4,3,2,1]' },
      { input: 'head = [1,2]', expectedOutput: '[2,1]' },
      { input: 'head = []', expectedOutput: '[]', isHidden: true },
    ],
  },
  {
    title: 'Merge Two Sorted Lists',
    description: 'Merge two sorted linked lists and return it as one sorted list.',
    difficulty: 'EASY',
    topic: 'Linked Lists',
    examples: [{ input: 'l1 = [1,2,4], l2 = [1,3,4]', output: '[1,1,2,3,4,4]' }],
    constraints: ['0 <= number of nodes <= 50', '-100 <= Node.val <= 100'],
    sampleInput: 'l1 = [1,2,4], l2 = [1,3,4]',
    sampleOutput: '[1,1,2,3,4,4]',
    testCases: [
      { input: 'l1 = [1,2,4], l2 = [1,3,4]', expectedOutput: '[1,1,2,3,4,4]' },
      { input: 'l1 = [], l2 = []', expectedOutput: '[]' },
      { input: 'l1 = [], l2 = [0]', expectedOutput: '[0]', isHidden: true },
    ],
  },
  {
    title: 'Remove Linked List Elements',
    description: 'Remove all elements from a linked list that have the given value.',
    difficulty: 'EASY',
    topic: 'Linked Lists',
    examples: [{ input: 'head = [1,2,6,3,4,5,6], val = 6', output: '[1,2,3,4,5]' }],
    constraints: ['0 <= number of nodes <= 50', '0 <= Node.val <= 100'],
    sampleInput: 'head = [1,2,6,3,4,5,6], val = 6',
    sampleOutput: '[1,2,3,4,5]',
    testCases: [
      { input: 'head = [1,2,6,3,4,5,6], val = 6', expectedOutput: '[1,2,3,4,5]' },
      { input: 'head = [] , val = 1', expectedOutput: '[]' },
      { input: 'head = [7,7,7], val = 7', expectedOutput: '[]', isHidden: true },
    ],
  },
  {
    title: 'Palindrome Linked List',
    description: 'Check whether a linked list is a palindrome.',
    difficulty: 'EASY',
    topic: 'Linked Lists',
    examples: [{ input: 'head = [1,2,2,1]', output: 'true' }],
    constraints: ['1 <= number of nodes <= 10^5', '0 <= Node.val <= 9'],
    sampleInput: 'head = [1,2,2,1]',
    sampleOutput: 'true',
    testCases: [
      { input: 'head = [1,2,2,1]', expectedOutput: 'true' },
      { input: 'head = [1,2]', expectedOutput: 'false' },
      { input: 'head = [1]', expectedOutput: 'true', isHidden: true },
    ],
  },
  {
    title: 'Delete Node in a Linked List',
    description: 'Delete a node in a singly linked list given only access to that node.',
    difficulty: 'EASY',
    topic: 'Linked Lists',
    examples: [{ input: 'head = [4,5,1,9], node = 5', output: '[4,1,9]' }],
    constraints: ['2 <= number of nodes <= 100', 'The node to delete is not the tail.'],
    sampleInput: 'head = [4,5,1,9], node = 5',
    sampleOutput: '[4,1,9]',
    testCases: [
      { input: 'head = [4,5,1,9], node = 5', expectedOutput: '[4,1,9]' },
      { input: 'head = [1,2], node = 1', expectedOutput: '[2]' },
      { input: 'head = [1,2,3], node = 2', expectedOutput: '[1,3]', isHidden: true },
    ],
  },
  {
    title: 'Linked List Cycle',
    description: 'Detect whether a linked list contains a cycle.',
    difficulty: 'EASY',
    topic: 'Linked Lists',
    examples: [{ input: 'head = [3,2,0,-4], pos = 1', output: 'true' }],
    constraints: ['0 <= number of nodes <= 10^4', '-10^5 <= Node.val <= 10^5'],
    sampleInput: 'head = [3,2,0,-4], pos = 1',
    sampleOutput: 'true',
    testCases: [
      { input: 'head = [3,2,0,-4], pos = 1', expectedOutput: 'true' },
      { input: 'head = [1,2], pos = 0', expectedOutput: 'true' },
      { input: 'head = [1], pos = -1', expectedOutput: 'false', isHidden: true },
    ],
  },
  {
    title: 'Intersection of Two Linked Lists',
    description: 'Find the node at which two singly linked lists intersect.',
    difficulty: 'EASY',
    topic: 'Linked Lists',
    examples: [{ input: 'listA = [4,1,8,4,5], listB = [5,6,1,8,4,5]', output: '8' }],
    constraints: ['0 <= number of nodes <= 3 * 10^4', '1 <= Node.val <= 10^5'],
    sampleInput: 'listA = [4,1,8,4,5], listB = [5,6,1,8,4,5]',
    sampleOutput: '8',
    testCases: [
      { input: 'listA = [4,1,8,4,5], listB = [5,6,1,8,4,5]', expectedOutput: '8' },
      { input: 'listA = [1,9,1,2,4], listB = [3,2,4]', expectedOutput: '2' },
      { input: 'listA = [2,6,4], listB = [1,5]', expectedOutput: 'null', isHidden: true },
    ],
  },
  {
    title: 'Add Two Numbers',
    description: 'Add two numbers represented by linked lists and return the sum as a linked list.',
    difficulty: 'EASY',
    topic: 'Linked Lists',
    examples: [{ input: 'l1 = [2,4,3], l2 = [5,6,4]', output: '[7,0,8]' }],
    constraints: ['1 <= number of nodes <= 100', '0 <= Node.val <= 9'],
    sampleInput: 'l1 = [2,4,3], l2 = [5,6,4]',
    sampleOutput: '[7,0,8]',
    testCases: [
      { input: 'l1 = [2,4,3], l2 = [5,6,4]', expectedOutput: '[7,0,8]' },
      { input: 'l1 = [0], l2 = [0]', expectedOutput: '[0]' },
      {
        input: 'l1 = [9,9,9,9,9,9,9], l2 = [9,9,9,9]',
        expectedOutput: '[8,9,9,9,0,0,0,1]',
        isHidden: true,
      },
    ],
  },
  {
    title: 'Odd Even Linked List',
    description: 'Group odd-indexed nodes followed by even-indexed nodes while preserving order.',
    difficulty: 'MEDIUM',
    topic: 'Linked Lists',
    examples: [{ input: 'head = [1,2,3,4,5]', output: '[1,3,5,2,4]' }],
    constraints: ['0 <= number of nodes <= 10^4', '-10^6 <= Node.val <= 10^6'],
    sampleInput: 'head = [1,2,3,4,5]',
    sampleOutput: '[1,3,5,2,4]',
    testCases: [
      { input: 'head = [1,2,3,4,5]', expectedOutput: '[1,3,5,2,4]' },
      { input: 'head = [2,1,3,5,6,4,7]', expectedOutput: '[2,3,6,7,1,5,4]' },
      { input: 'head = []', expectedOutput: '[]', isHidden: true },
    ],
  },
  {
    title: 'Remove Nth Node From End of List',
    description: 'Remove the n-th node from the end of a linked list and return its head.',
    difficulty: 'MEDIUM',
    topic: 'Linked Lists',
    examples: [{ input: 'head = [1,2,3,4,5], n = 2', output: '[1,2,3,5]' }],
    constraints: ['1 <= number of nodes <= 30', '1 <= n <= length of list'],
    sampleInput: 'head = [1,2,3,4,5], n = 2',
    sampleOutput: '[1,2,3,5]',
    testCases: [
      { input: 'head = [1,2,3,4,5], n = 2', expectedOutput: '[1,2,3,5]' },
      { input: 'head = [1], n = 1', expectedOutput: '[]' },
      { input: 'head = [1,2], n = 1', expectedOutput: '[1]', isHidden: true },
    ],
  },
  {
    title: 'Swap Nodes in Pairs',
    description: 'Swap every two adjacent nodes in a linked list.',
    difficulty: 'MEDIUM',
    topic: 'Linked Lists',
    examples: [{ input: 'head = [1,2,3,4]', output: '[2,1,4,3]' }],
    constraints: ['0 <= number of nodes <= 100', '0 <= Node.val <= 100'],
    sampleInput: 'head = [1,2,3,4]',
    sampleOutput: '[2,1,4,3]',
    testCases: [
      { input: 'head = [1,2,3,4]', expectedOutput: '[2,1,4,3]' },
      { input: 'head = [1,2,3]', expectedOutput: '[2,1,3]' },
      { input: 'head = []', expectedOutput: '[]', isHidden: true },
    ],
  },
  {
    title: 'Rotate List',
    description: 'Rotate a list to the right by k places.',
    difficulty: 'MEDIUM',
    topic: 'Linked Lists',
    examples: [{ input: 'head = [1,2,3,4,5], k = 2', output: '[4,5,1,2,3]' }],
    constraints: ['0 <= number of nodes <= 500', '0 <= k <= 2 * 10^9'],
    sampleInput: 'head = [1,2,3,4,5], k = 2',
    sampleOutput: '[4,5,1,2,3]',
    testCases: [
      { input: 'head = [1,2,3,4,5], k = 2', expectedOutput: '[4,5,1,2,3]' },
      { input: 'head = [0,1,2], k = 4', expectedOutput: '[2,0,1]' },
      { input: 'head = [], k = 0', expectedOutput: '[]', isHidden: true },
    ],
  },
  {
    title: 'Partition List',
    description:
      'Partition a linked list so that nodes less than x come before nodes greater than or equal to x.',
    difficulty: 'MEDIUM',
    topic: 'Linked Lists',
    examples: [{ input: 'head = [1,4,3,2,5,2], x = 3', output: '[1,2,2,4,3,5]' }],
    constraints: ['0 <= number of nodes <= 200', '-100 <= Node.val <= 100'],
    sampleInput: 'head = [1,4,3,2,5,2], x = 3',
    sampleOutput: '[1,2,2,4,3,5]',
    testCases: [
      { input: 'head = [1,4,3,2,5,2], x = 3', expectedOutput: '[1,2,2,4,3,5]' },
      { input: 'head = [2,1], x = 2', expectedOutput: '[1,2]' },
      { input: 'head = [3,3,3], x = 3', expectedOutput: '[3,3,3]', isHidden: true },
    ],
  },
  {
    title: 'Sort List',
    description: 'Sort a linked list in O(n log n) time and return its head.',
    difficulty: 'MEDIUM',
    topic: 'Linked Lists',
    examples: [{ input: 'head = [4,2,1,3]', output: '[1,2,3,4]' }],
    constraints: ['0 <= number of nodes <= 5 * 10^4', '-10^5 <= Node.val <= 10^5'],
    sampleInput: 'head = [4,2,1,3]',
    sampleOutput: '[1,2,3,4]',
    testCases: [
      { input: 'head = [4,2,1,3]', expectedOutput: '[1,2,3,4]' },
      { input: 'head = [-1,5,3,4,0]', expectedOutput: '[-1,0,3,4,5]' },
      { input: 'head = []', expectedOutput: '[]', isHidden: true },
    ],
  },
  {
    title: 'Remove Duplicates from Sorted List',
    description: 'Delete all duplicates such that each element appears only once.',
    difficulty: 'MEDIUM',
    topic: 'Linked Lists',
    examples: [{ input: 'head = [1,1,2]', output: '[1,2]' }],
    constraints: ['0 <= number of nodes <= 300', '-100 <= Node.val <= 100'],
    sampleInput: 'head = [1,1,2]',
    sampleOutput: '[1,2]',
    testCases: [
      { input: 'head = [1,1,2]', expectedOutput: '[1,2]' },
      { input: 'head = [1,1,2,3,3]', expectedOutput: '[1,2,3]' },
      { input: 'head = []', expectedOutput: '[]', isHidden: true },
    ],
  },
  {
    title: 'Reverse Nodes in k-Group',
    description: 'Reverse the nodes of a list k at a time and return the modified list.',
    difficulty: 'HARD',
    topic: 'Linked Lists',
    examples: [{ input: 'head = [1,2,3,4,5], k = 2', output: '[2,1,4,3,5]' }],
    constraints: ['1 <= number of nodes <= 5000', '1 <= k <= 5000'],
    sampleInput: 'head = [1,2,3,4,5], k = 2',
    sampleOutput: '[2,1,4,3,5]',
    testCases: [
      { input: 'head = [1,2,3,4,5], k = 2', expectedOutput: '[2,1,4,3,5]' },
      { input: 'head = [1,2,3,4,5], k = 3', expectedOutput: '[3,2,1,4,5]' },
      { input: 'head = [1], k = 1', expectedOutput: '[1]', isHidden: true },
    ],
  },
  {
    title: 'Linked List Cycle II',
    description: 'Return the node where the cycle begins, or null if no cycle exists.',
    difficulty: 'HARD',
    topic: 'Linked Lists',
    examples: [{ input: 'head = [3,2,0,-4], pos = 1', output: '2' }],
    constraints: ['0 <= number of nodes <= 10^4', '-10^5 <= Node.val <= 10^5'],
    sampleInput: 'head = [3,2,0,-4], pos = 1',
    sampleOutput: '2',
    testCases: [
      { input: 'head = [3,2,0,-4], pos = 1', expectedOutput: '2' },
      { input: 'head = [1,2], pos = 0', expectedOutput: '1' },
      { input: 'head = [1], pos = -1', expectedOutput: 'null', isHidden: true },
    ],
  },
  {
    title: 'Copy List with Random Pointer',
    description: 'Create a deep copy of a linked list where each node has a random pointer.',
    difficulty: 'HARD',
    topic: 'Linked Lists',
    examples: [
      {
        input: '[[7,null],[13,0],[11,4],[10,2],[1,0]]',
        output: '[[7,null],[13,0],[11,4],[10,2],[1,0]]',
      },
    ],
    constraints: ['0 <= number of nodes <= 1000', '0 <= Node.val <= 10^4'],
    sampleInput: '[[7,null],[13,0],[11,4],[10,2],[1,0]]',
    sampleOutput: '[[7,null],[13,0],[11,4],[10,2],[1,0]]',
    testCases: [
      {
        input: '[[7,null],[13,0],[11,4],[10,2],[1,0]]',
        expectedOutput: '[[7,null],[13,0],[11,4],[10,2],[1,0]]',
      },
      { input: '[[1,1],[2,1]]', expectedOutput: '[[1,1],[2,1]]' },
      {
        input: '[[3,3],[3,null],[3,null]]',
        expectedOutput: '[[3,3],[3,null],[3,null]]',
        isHidden: true,
      },
    ],
  },
  {
    title: 'Reorder List',
    description: 'Reorder a linked list in-place from L0 → Ln → L1 → Ln-1 → L2 → Ln-2 → ...',
    difficulty: 'HARD',
    topic: 'Linked Lists',
    examples: [{ input: 'head = [1,2,3,4]', output: '[1,4,2,3]' }],
    constraints: ['1 <= number of nodes <= 5 * 10^4', '-1000 <= Node.val <= 1000'],
    sampleInput: 'head = [1,2,3,4]',
    sampleOutput: '[1,4,2,3]',
    testCases: [
      { input: 'head = [1,2,3,4]', expectedOutput: '[1,4,2,3]' },
      { input: 'head = [1,2,3,4,5]', expectedOutput: '[1,5,2,4,3]' },
      { input: 'head = [1]', expectedOutput: '[1]', isHidden: true },
    ],
  },
  {
    title: 'Split Linked List in Parts',
    description: 'Split a linked list into k parts of nearly equal size.',
    difficulty: 'HARD',
    topic: 'Linked Lists',
    examples: [{ input: 'head = [1,2,3,4,5,6,7], k = 3', output: '[[1,2,3],[4,5],[6,7]]' }],
    constraints: ['0 <= number of nodes <= 1000', '1 <= k <= 50'],
    sampleInput: 'head = [1,2,3,4,5,6,7], k = 3',
    sampleOutput: '[[1,2,3],[4,5],[6,7]]',
    testCases: [
      { input: 'head = [1,2,3,4,5,6,7], k = 3', expectedOutput: '[[1,2,3],[4,5],[6,7]]' },
      { input: 'head = [1,2,3], k = 5', expectedOutput: '[[1],[2],[3],[],[]]' },
      { input: 'head = [], k = 3', expectedOutput: '[[],[],[]]', isHidden: true },
    ],
  },
  {
    title: 'Merge k Sorted Lists',
    description: 'Merge k sorted linked lists and return it as one sorted list.',
    difficulty: 'HARD',
    topic: 'Linked Lists',
    examples: [{ input: 'lists = [[1,4,5],[1,3,4],[2,6]]', output: '[1,1,2,3,4,4,5,6]' }],
    constraints: ['k == lists.length', '0 <= k <= 10^4'],
    sampleInput: 'lists = [[1,4,5],[1,3,4],[2,6]]',
    sampleOutput: '[1,1,2,3,4,4,5,6]',
    testCases: [
      { input: 'lists = [[1,4,5],[1,3,4],[2,6]]', expectedOutput: '[1,1,2,3,4,4,5,6]' },
      { input: 'lists = []', expectedOutput: '[]' },
      { input: 'lists = [[]]', expectedOutput: '[]', isHidden: true },
    ],
  },

  // Stacks - Easy
  {
    title: 'Valid Parentheses',
    description: 'Determine whether a string of parentheses is valid.',
    difficulty: 'EASY',
    topic: 'Stacks',
    examples: [{ input: 's = "()[]{}"', output: 'true' }],
    constraints: ['1 <= s.length <= 10^4', 's consists of parentheses only.'],
    sampleInput: 's = "()[]{}"',
    sampleOutput: 'true',
    testCases: [
      { input: 's = "()"', expectedOutput: 'true' },
      { input: 's = "(]"', expectedOutput: 'false' },
      { input: 's = "([)]"', expectedOutput: 'false', isHidden: true },
    ],
  },
  {
    title: 'Evaluate Reverse Polish Notation',
    description: 'Evaluate an arithmetic expression in Reverse Polish Notation.',
    difficulty: 'EASY',
    topic: 'Stacks',
    examples: [{ input: 'tokens = ["2","1","+","3","*"]', output: '9' }],
    constraints: ['1 <= tokens.length <= 10^4', 'tokens[i] is an integer or operator.'],
    sampleInput: 'tokens = ["2","1","+","3","*"]',
    sampleOutput: '9',
    testCases: [
      { input: 'tokens = ["2","1","+","3","*"]', expectedOutput: '9' },
      { input: 'tokens = ["4","13","5","/","+"]', expectedOutput: '6' },
      {
        input: 'tokens = ["10","6","9","3","+","-11","*","/","*","17","+","5","+"]',
        expectedOutput: '22',
        isHidden: true,
      },
    ],
  },
  {
    title: 'Min Stack',
    description:
      'Design a stack that supports push, pop, top, and retrieving the minimum element in constant time.',
    difficulty: 'EASY',
    topic: 'Stacks',
    examples: [
      {
        input: 'push(-2), push(0), push(-3), getMin(), pop(), top(), getMin()',
        output: '[-3,0,-2]',
      },
    ],
    constraints: ['Methods called at most 3 * 10^4 times', '-10^5 <= value <= 10^5'],
    sampleInput: 'push(-2), push(0), push(-3), getMin(), pop(), top(), getMin()',
    sampleOutput: '[-3,0,-2]',
    testCases: [
      {
        input: 'push(-2), push(0), push(-3), getMin(), pop(), top(), getMin()',
        expectedOutput: '[-3,0,-2]',
      },
      { input: 'push(1), push(2), getMin(), pop(), getMin()', expectedOutput: '[1,1]' },
      {
        input: 'push(2), push(2), getMin(), pop(), getMin()',
        expectedOutput: '[2,2]',
        isHidden: true,
      },
    ],
  },
  {
    title: 'Simplify Path',
    description: 'Simplify a Unix-style file path.',
    difficulty: 'EASY',
    topic: 'Stacks',
    examples: [{ input: 'path = "/a/./b/../../c/"', output: '/c' }],
    constraints: ['1 <= path.length <= 3000', 'path is a valid absolute Unix path.'],
    sampleInput: 'path = "/a/./b/../../c/"',
    sampleOutput: '/c',
    testCases: [
      { input: 'path = "/home/"', expectedOutput: '/home' },
      { input: 'path = "/../"', expectedOutput: '/' },
      { input: 'path = "/home//foo/"', expectedOutput: '/home/foo', isHidden: true },
    ],
  },
  {
    title: 'Score of Parentheses',
    description: 'Compute the score of a balanced parentheses string.',
    difficulty: 'EASY',
    topic: 'Stacks',
    examples: [{ input: 's = "()"', output: '1' }],
    constraints: ['2 <= s.length <= 50', 's is balanced parentheses.'],
    sampleInput: 's = "()"',
    sampleOutput: '1',
    testCases: [
      { input: 's = "()"', expectedOutput: '1' },
      { input: 's = "(())"', expectedOutput: '2' },
      { input: 's = "()()"', expectedOutput: '2', isHidden: true },
    ],
  },
  {
    title: 'Backspace String Compare',
    description: 'Compare two strings after processing backspace characters (#).',
    difficulty: 'EASY',
    topic: 'Stacks',
    examples: [{ input: 's = "ab#c", t = "ad#c"', output: 'true' }],
    constraints: ['1 <= s.length, t.length <= 200', 's and t contain letters and #.'],
    sampleInput: 's = "ab#c", t = "ad#c"',
    sampleOutput: 'true',
    testCases: [
      { input: 's = "ab#c", t = "ad#c"', expectedOutput: 'true' },
      { input: 's = "a##c", t = "#a#c"', expectedOutput: 'true' },
      { input: 's = "a#c", t = "b"', expectedOutput: 'false', isHidden: true },
    ],
  },
  {
    title: 'Baseball Game',
    description: 'Calculate the total score from a list of operations in a baseball game.',
    difficulty: 'EASY',
    topic: 'Stacks',
    examples: [{ input: 'ops = ["5","2","C","D","+"]', output: '30' }],
    constraints: ['1 <= ops.length <= 1000', 'ops[i] is valid.'],
    sampleInput: 'ops = ["5","2","C","D","+"]',
    sampleOutput: '30',
    testCases: [
      { input: 'ops = ["5","2","C","D","+"]', expectedOutput: '30' },
      { input: 'ops = ["5","-2","4","C","D","9","+","+"]', expectedOutput: '27' },
      { input: 'ops = ["1"]', expectedOutput: '1', isHidden: true },
    ],
  },
  {
    title: 'Valid Parentheses II',
    description:
      'Check whether a string containing parentheses and * can be valid by treating * as (, ), or empty.',
    difficulty: 'MEDIUM',
    topic: 'Stacks',
    examples: [{ input: 's = "(*)"', output: 'true' }],
    constraints: ['1 <= s.length <= 100', 's contains (, ), and *.'],
    sampleInput: 's = "(*)"',
    sampleOutput: 'true',
    testCases: [
      { input: 's = "(*)"', expectedOutput: 'true' },
      { input: 's = "(*))"', expectedOutput: 'true' },
      { input: 's = "((*)"', expectedOutput: 'false', isHidden: true },
    ],
  },
  {
    title: 'Implement Stack using Queues',
    description: 'Implement a LIFO stack using only two FIFO queues.',
    difficulty: 'MEDIUM',
    topic: 'Stacks',
    examples: [{ input: 'push(1), push(2), top(), pop(), empty()', output: '[2,2,false]' }],
    constraints: ['1 <= x <= 10^9', 'At most 100 calls will be made.'],
    sampleInput: 'push(1), push(2), top(), pop(), empty()',
    sampleOutput: '[2,2,false]',
    testCases: [
      { input: 'push(1), push(2), top(), pop(), empty()', expectedOutput: '[2,2,false]' },
      { input: 'push(5), push(3), pop(), top()', expectedOutput: '[3,5]' },
      { input: 'empty()', expectedOutput: 'true', isHidden: true },
    ],
  },
  {
    title: 'Decode String',
    description: 'Decode an encoded string with numbers and nested brackets.',
    difficulty: 'MEDIUM',
    topic: 'Stacks',
    examples: [{ input: 's = "3[a]2[bc]"', output: 'aaabcbc' }],
    constraints: ['1 <= s.length <= 30', 's consists of letters, digits, and brackets.'],
    sampleInput: 's = "3[a]2[bc]"',
    sampleOutput: 'aaabcbc',
    testCases: [
      { input: 's = "3[a]2[bc]"', expectedOutput: 'aaabcbc' },
      { input: 's = "3[a2[c]]"', expectedOutput: 'accaccacc' },
      { input: 's = "2[abc]3[cd]ef"', expectedOutput: 'abcabccdcdcdef', isHidden: true },
    ],
  },
  {
    title: 'Basic Calculator II',
    description: 'Evaluate a simple arithmetic expression string containing +, -, *, and /.',
    difficulty: 'MEDIUM',
    topic: 'Stacks',
    examples: [{ input: 's = "3+2*2"', output: '7' }],
    constraints: ['1 <= s.length <= 3 * 10^5', 's contains digits and operators.'],
    sampleInput: 's = "3+2*2"',
    sampleOutput: '7',
    testCases: [
      { input: 's = " 3/2 "', expectedOutput: '1' },
      { input: 's = " 3+5 / 2 "', expectedOutput: '5' },
      { input: 's = "14-3/2"', expectedOutput: '13', isHidden: true },
    ],
  },
  {
    title: 'Daily Temperatures',
    description: 'Return the number of days until a warmer temperature for each day.',
    difficulty: 'MEDIUM',
    topic: 'Stacks',
    examples: [{ input: 'temperatures = [73,74,75,71,69,72,76,73]', output: '[1,1,4,2,1,1,0,0]' }],
    constraints: ['1 <= temperatures.length <= 10^5', '30 <= temperatures[i] <= 100'],
    sampleInput: 'temperatures = [73,74,75,71,69,72,76,73]',
    sampleOutput: '[1,1,4,2,1,1,0,0]',
    testCases: [
      { input: 'temperatures = [30,40,50,60]', expectedOutput: '[1,1,1,0]' },
      { input: 'temperatures = [30,60,90]', expectedOutput: '[1,1,0]' },
      { input: 'temperatures = [90,80,70]', expectedOutput: '[0,0,0]', isHidden: true },
    ],
  },
  {
    title: 'Next Greater Element I',
    description: 'For each element in nums1, find the next greater element in nums2.',
    difficulty: 'MEDIUM',
    topic: 'Stacks',
    examples: [{ input: 'nums1 = [4,1,2], nums2 = [1,3,4,2]', output: '[-1,3,-1]' }],
    constraints: [
      '1 <= nums1.length <= nums2.length <= 1000',
      'nums1 and nums2 contain unique values.',
    ],
    sampleInput: 'nums1 = [4,1,2], nums2 = [1,3,4,2]',
    sampleOutput: '[-1,3,-1]',
    testCases: [
      { input: 'nums1 = [2,4], nums2 = [1,2,3,4]', expectedOutput: '[3,-1]' },
      { input: 'nums1 = [1,3,5,2,4], nums2 = [6,5,4,3,2,1,7]', expectedOutput: '[7,7,7,7,7]' },
      { input: 'nums1 = [1], nums2 = [1]', expectedOutput: '[-1]', isHidden: true },
    ],
  },
  {
    title: 'Next Greater Element II',
    description: 'Find the next greater element for each element in a circular array.',
    difficulty: 'MEDIUM',
    topic: 'Stacks',
    examples: [{ input: 'nums = [1,2,1]', output: '[2,-1,2]' }],
    constraints: ['1 <= nums.length <= 10^4', '-10^9 <= nums[i] <= 10^9'],
    sampleInput: 'nums = [1,2,1]',
    sampleOutput: '[2,-1,2]',
    testCases: [
      { input: 'nums = [1,2,3,4,3]', expectedOutput: '[2,3,4,-1,4]' },
      { input: 'nums = [2,2,2]', expectedOutput: '[-1,-1,-1]' },
      { input: 'nums = [5,4,3,2,1]', expectedOutput: '[-1,5,5,5,5]', isHidden: true },
    ],
  },
  {
    title: 'Validate Stack Sequences',
    description: 'Check whether a pushed and popped sequence is valid for a stack.',
    difficulty: 'MEDIUM',
    topic: 'Stacks',
    examples: [{ input: 'pushed = [1,2,3,4,5], popped = [4,5,3,2,1]', output: 'true' }],
    constraints: ['1 <= pushed.length <= 1000', 'pushed and popped are permutations.'],
    sampleInput: 'pushed = [1,2,3,4,5], popped = [4,5,3,2,1]',
    sampleOutput: 'true',
    testCases: [
      { input: 'pushed = [1,2,3,4,5], popped = [4,5,3,2,1]', expectedOutput: 'true' },
      { input: 'pushed = [1,2,3,4,5], popped = [4,3,5,1,2]', expectedOutput: 'false' },
      { input: 'pushed = [2,1,0], popped = [1,2,0]', expectedOutput: 'true', isHidden: true },
    ],
  },
  {
    title: 'Trapping Rain Water',
    description: 'Given heights of bars in a histogram, compute how much water can be trapped.',
    difficulty: 'HARD',
    topic: 'Stacks',
    examples: [{ input: 'height = [0,1,0,2,1,0,1,3,2,1,2,1]', output: '6' }],
    constraints: ['1 <= height.length <= 10^5', '0 <= height[i] <= 10^4'],
    sampleInput: 'height = [0,1,0,2,1,0,1,3,2,1,2,1]',
    sampleOutput: '6',
    testCases: [
      { input: 'height = [4,2,0,3,2,5]', expectedOutput: '9' },
      { input: 'height = [2,0,2]', expectedOutput: '2' },
      { input: 'height = [1,0,2]', expectedOutput: '1', isHidden: true },
    ],
  },
  {
    title: 'Largest Rectangle in Histogram',
    description: 'Find the area of the largest rectangle in a histogram.',
    difficulty: 'HARD',
    topic: 'Stacks',
    examples: [{ input: 'heights = [2,1,5,6,2,3]', output: '10' }],
    constraints: ['1 <= heights.length <= 10^5', '0 <= heights[i] <= 10^4'],
    sampleInput: 'heights = [2,1,5,6,2,3]',
    sampleOutput: '10',
    testCases: [
      { input: 'heights = [2,4]', expectedOutput: '4' },
      { input: 'heights = [1,1]', expectedOutput: '2' },
      { input: 'heights = [2,3,2]', expectedOutput: '6', isHidden: true },
    ],
  },
  {
    title: 'Basic Calculator',
    description:
      'Evaluate a simple arithmetic expression string containing +, -, parentheses, and spaces.',
    difficulty: 'HARD',
    topic: 'Stacks',
    examples: [{ input: 's = "1 + 1"', output: '2' }],
    constraints: [
      '1 <= s.length <= 3 * 10^5',
      's consists of digits, +, -, parentheses, and spaces.',
    ],
    sampleInput: 's = "1 + 1"',
    sampleOutput: '2',
    testCases: [
      { input: 's = " 2-1 + 2 "', expectedOutput: '3' },
      { input: 's = "(1+(4+5+2)-3)+(6+8)"', expectedOutput: '23' },
      { input: 's = "(1+2)-(3-4)"', expectedOutput: '4', isHidden: true },
    ],
  },

  // Queues - Easy
  {
    title: 'Implement Queue using Stacks',
    description: 'Implement a FIFO queue using only two stacks.',
    difficulty: 'EASY',
    topic: 'Queues',
    examples: [{ input: 'push(1), push(2), peek(), pop(), empty()', output: '[1,1,false]' }],
    constraints: ['1 <= x <= 9', 'At most 100 calls will be made.'],
    sampleInput: 'push(1), push(2), peek(), pop(), empty()',
    sampleOutput: '[1,1,false]',
    testCases: [
      { input: 'push(1), push(2), peek(), pop(), empty()', expectedOutput: '[1,1,false]' },
      { input: 'push(5), push(6), pop(), peek()', expectedOutput: '[5,6]' },
      { input: 'empty()', expectedOutput: 'true', isHidden: true },
    ],
  },
  {
    title: 'Moving Average from Data Stream',
    description: 'Calculate the moving average of values in a sliding window stream.',
    difficulty: 'EASY',
    topic: 'Queues',
    examples: [
      {
        input: 'MovingAverage(3), next(1), next(10), next(3), next(5)',
        output: '[null,1.0,5.5,4.666666666666667,6.0]',
      },
    ],
    constraints: ['1 <= size <= 1000', '-10^5 <= val <= 10^5'],
    sampleInput: 'MovingAverage(3), next(1), next(10), next(3), next(5)',
    sampleOutput: '[null,1.0,5.5,4.666666666666667,6.0]',
    testCases: [
      {
        input: 'MovingAverage(3), next(1), next(10), next(3), next(5)',
        expectedOutput: '[null,1.0,5.5,4.666666666666667,6.0]',
      },
      { input: 'MovingAverage(1), next(10), next(-1)', expectedOutput: '[null,10.0,-1.0]' },
      {
        input: 'MovingAverage(2), next(5), next(7)',
        expectedOutput: '[null,5.0,6.0]',
        isHidden: true,
      },
    ],
  },
  {
    title: 'Design Circular Queue',
    description:
      'Design a circular queue with fixed capacity supporting enqueue, dequeue, front, rear, and empty/full checks.',
    difficulty: 'EASY',
    topic: 'Queues',
    examples: [
      {
        input: 'MyCircularQueue(3), enQueue(1), enQueue(2), enQueue(3), deQueue(), Front()',
        output: '[true,true,true,true,true,2]',
      },
    ],
    constraints: ['1 <= k <= 1000', 'At most 1000 calls will be made.'],
    sampleInput: 'MyCircularQueue(3), enQueue(1), enQueue(2), enQueue(3), deQueue(), Front()',
    sampleOutput: '[true,true,true,true,true,2]',
    testCases: [
      {
        input: 'MyCircularQueue(3), enQueue(1), enQueue(2), enQueue(3), deQueue(), Front()',
        expectedOutput: '[true,true,true,true,true,2]',
      },
      {
        input: 'MyCircularQueue(2), enQueue(2), enQueue(3), deQueue(), enQueue(4), Rear()',
        expectedOutput: '[true,true,true,true,4]',
      },
      {
        input: 'MyCircularQueue(1), enQueue(1), enQueue(2)',
        expectedOutput: '[true,false]',
        isHidden: true,
      },
    ],
  },
  {
    title: 'Number of Recent Calls',
    description:
      'Implement a recent counter that counts the number of requests in the past 3000 milliseconds.',
    difficulty: 'EASY',
    topic: 'Queues',
    examples: [{ input: 'Pings(1), Pings(100), Pings(3001), Pings(3002)', output: '[1,2,3,3]' }],
    constraints: ['1 <= t <= 10^9', 'At most 10^4 calls will be made.'],
    sampleInput: 'Pings(1), Pings(100), Pings(3001), Pings(3002)',
    sampleOutput: '[1,2,3,3]',
    testCases: [
      { input: 'Pings(1), Pings(100), Pings(3001), Pings(3002)', expectedOutput: '[1,2,3,3]' },
      { input: 'Pings(3000), Pings(6000)', expectedOutput: '[1,1]' },
      { input: 'Pings(1), Pings(3000), Pings(3001)', expectedOutput: '[1,2,3]', isHidden: true },
    ],
  },
  {
    title: 'Implement Stack using Queues',
    description: 'Implement a stack using only two queues.',
    difficulty: 'MEDIUM',
    topic: 'Queues',
    examples: [{ input: 'push(1), push(2), top(), pop(), empty()', output: '[2,2,false]' }],
    constraints: ['1 <= x <= 10^9', 'At most 100 calls will be made.'],
    sampleInput: 'push(1), push(2), top(), pop(), empty()',
    sampleOutput: '[2,2,false]',
    testCases: [
      { input: 'push(1), push(2), top(), pop(), empty()', expectedOutput: '[2,2,false]' },
      { input: 'push(3), push(4), pop(), top()', expectedOutput: '[4,3]' },
      { input: 'empty()', expectedOutput: 'true', isHidden: true },
    ],
  },
  {
    title: 'Open the Lock',
    description:
      'Find the minimum number of moves to open a lock using a 4-digit wheel configuration.',
    difficulty: 'MEDIUM',
    topic: 'Queues',
    examples: [
      { input: 'deadends = ["0201","0101","0102","1212","2002"], target = "0202"', output: '6' },
    ],
    constraints: ['1 <= deadends.length <= 500', 'target.length == 4'],
    sampleInput: 'deadends = ["0201","0101","0102","1212","2002"], target = "0202"',
    sampleOutput: '6',
    testCases: [
      {
        input: 'deadends = ["0201","0101","0102","1212","2002"], target = "0202"',
        expectedOutput: '6',
      },
      { input: 'deadends = ["8888"], target = "0009"', expectedOutput: '1' },
      {
        input:
          'deadends = ["8887","8889","8878","8898","8788","8988","7888","9888"], target = "8888"',
        expectedOutput: '-1',
        isHidden: true,
      },
    ],
  },
  {
    title: 'Perfect Squares',
    description: 'Return the least number of perfect square numbers which sum to n.',
    difficulty: 'MEDIUM',
    topic: 'Queues',
    examples: [{ input: 'n = 12', output: '3' }],
    constraints: ['1 <= n <= 10^4'],
    sampleInput: 'n = 12',
    sampleOutput: '3',
    testCases: [
      { input: 'n = 12', expectedOutput: '3' },
      { input: 'n = 13', expectedOutput: '2' },
      { input: 'n = 1', expectedOutput: '1', isHidden: true },
    ],
  },
  {
    title: 'Walls and Gates',
    description: 'Fill each empty room with the distance to its nearest gate.',
    difficulty: 'MEDIUM',
    topic: 'Queues',
    examples: [
      {
        input:
          'rooms = [[2147483647,-1,0,2147483647],[2147483647,2147483647,2147483647,-1],[2147483647,-1,2147483647,-1],[0,-1,2147483647,2147483647]]',
        output: '[[3,-1,0,1],[2,2,1,-1],[1,-1,2,-1],[0,-1,3,4]]',
      },
    ],
    constraints: ['m == rooms.length', '1 <= m, n <= 250'],
    sampleInput:
      'rooms = [[2147483647,-1,0,2147483647],[2147483647,2147483647,2147483647,-1],[2147483647,-1,2147483647,-1],[0,-1,2147483647,2147483647]]',
    sampleOutput: '[[3,-1,0,1],[2,2,1,-1],[1,-1,2,-1],[0,-1,3,4]]',
    testCases: [
      {
        input:
          'rooms = [[2147483647,-1,0,2147483647],[2147483647,2147483647,2147483647,-1],[2147483647,-1,2147483647,-1],[0,-1,2147483647,2147483647]]',
        expectedOutput: '[[3,-1,0,1],[2,2,1,-1],[1,-1,2,-1],[0,-1,3,4]]',
      },
      { input: 'rooms = [[0]]', expectedOutput: '[[0]]' },
      { input: 'rooms = [[2147483647]]', expectedOutput: '[[2147483647]]', isHidden: true },
    ],
  },
  {
    title: 'Perfect Number',
    description: 'Determine if a number is equal to the sum of its proper divisors.',
    difficulty: 'EASY',
    topic: 'Math',
    examples: [{ input: 'num = 28', output: 'true' }],
    constraints: ['1 <= num <= 10^8'],
    sampleInput: 'num = 28',
    sampleOutput: 'true',
    testCases: [
      { input: 'num = 28', expectedOutput: 'true' },
      { input: 'num = 6', expectedOutput: 'true' },
      { input: 'num = 496', expectedOutput: 'true', isHidden: true },
    ],
  },
  {
    title: 'Friend Circles',
    description: 'Compute the number of connected friend groups using matrix adjacency.',
    difficulty: 'MEDIUM',
    topic: 'Graphs',
    examples: [{ input: 'M = [[1,1,0],[1,1,0],[0,0,1]]', output: '2' }],
    constraints: ['1 <= n <= 300', 'M[i][j] is 0 or 1.'],
    sampleInput: 'M = [[1,1,0],[1,1,0],[0,0,1]]',
    sampleOutput: '2',
    testCases: [
      { input: 'M = [[1,1,0],[1,1,0],[0,0,1]]', expectedOutput: '2' },
      { input: 'M = [[1,0,0],[0,1,0],[0,0,1]]', expectedOutput: '3' },
      { input: 'M = [[1,1],[1,1]]', expectedOutput: '1', isHidden: true },
    ],
  },
  // ... additional problems will be appended here for all remaining topics
];
