import type { ProblemSeed } from '../seed.ts';

export const mathProblems: ProblemSeed[] = [
  // EASY (10)
  {
    title: 'Palindrome Number',
    slug: 'palindrome-number',
    description: 'Determine whether an integer is a palindrome without converting it to a string.',
    difficulty: 'EASY',
    topic: 'Math',
    examples: [{ input: 'x = 121', output: 'true' }],
    constraints: ['-2^31 <= x <= 2^31 - 1'],
    sampleInput: 'x = 121',
    sampleOutput: 'true',
    testCases: [
      { input: 'x = 121', expectedOutput: 'true' },
      { input: 'x = -121', expectedOutput: 'false' },
      { input: 'x = 10', expectedOutput: 'false', isHidden: true },
    ],
  },
  {
    title: 'Reverse Integer',
    slug: 'reverse-integer',
    description: 'Reverse digits of a 32-bit signed integer. Return 0 on overflow.',
    difficulty: 'EASY',
    topic: 'Math',
    examples: [{ input: 'x = 123', output: '321' }],
    constraints: ['-2^31 <= x <= 2^31 - 1'],
    sampleInput: 'x = 123',
    sampleOutput: '321',
    testCases: [
      { input: 'x = 123', expectedOutput: '321' },
      { input: 'x = -123', expectedOutput: '-321' },
      { input: 'x = 1534236469', expectedOutput: '0', isHidden: true },
    ],
  },
  {
    title: 'Count Digits',
    slug: 'count-digits',
    description:
      'Return the number of digits in the decimal representation of a non-negative integer.',
    difficulty: 'EASY',
    topic: 'Math',
    examples: [{ input: 'n = 12345', output: '5' }],
    constraints: ['0 <= n <= 10^18'],
    sampleInput: 'n = 12345',
    sampleOutput: '5',
    testCases: [
      { input: 'n = 0', expectedOutput: '1' },
      { input: 'n = 9', expectedOutput: '1' },
      { input: 'n = 1000000000000000000', expectedOutput: '19', isHidden: true },
    ],
  },
  {
    title: 'Armstrong Number',
    slug: 'armstrong-number',
    description: 'Check if a number is an Armstrong (narcissistic) number for its digit count.',
    difficulty: 'EASY',
    topic: 'Math',
    examples: [{ input: 'n = 153', output: 'true' }],
    constraints: ['0 <= n <= 10^6'],
    sampleInput: 'n = 153',
    sampleOutput: 'true',
    testCases: [
      { input: 'n = 153', expectedOutput: 'true' },
      { input: 'n = 370', expectedOutput: 'true' },
      { input: 'n = 123', expectedOutput: 'false', isHidden: true },
    ],
  },
  {
    title: 'GCD of Two Numbers',
    slug: 'gcd-of-two-numbers',
    description:
      'Compute the greatest common divisor (GCD) of two integers using Euclid’s algorithm.',
    difficulty: 'EASY',
    topic: 'Math',
    examples: [{ input: 'a = 48, b = 18', output: '6' }],
    constraints: ['1 <= a, b <= 10^9'],
    sampleInput: 'a = 48, b = 18',
    sampleOutput: '6',
    testCases: [
      { input: 'a = 48, b = 18', expectedOutput: '6' },
      { input: 'a = 7, b = 3', expectedOutput: '1' },
      { input: 'a = 1000000000, b = 2', expectedOutput: '2', isHidden: true },
    ],
  },
  {
    title: 'LCM of Two Numbers',
    slug: 'lcm-of-two-numbers',
    description: 'Compute the least common multiple (LCM) of two positive integers.',
    difficulty: 'EASY',
    topic: 'Math',
    examples: [{ input: 'a = 4, b = 6', output: '12' }],
    constraints: ['1 <= a, b <= 10^9'],
    sampleInput: 'a = 4, b = 6',
    sampleOutput: '12',
    testCases: [
      { input: 'a = 4, b = 6', expectedOutput: '12' },
      { input: 'a = 7, b = 3', expectedOutput: '21' },
      { input: 'a = 100000, b = 99991', expectedOutput: '9999100000', isHidden: true },
    ],
  },
  {
    title: 'Prime Check',
    slug: 'prime-check',
    description: 'Return whether a given integer is prime.',
    difficulty: 'EASY',
    topic: 'Math',
    examples: [{ input: 'n = 17', output: 'true' }],
    constraints: ['2 <= n <= 10^9'],
    sampleInput: 'n = 17',
    sampleOutput: 'true',
    testCases: [
      { input: 'n = 17', expectedOutput: 'true' },
      { input: 'n = 18', expectedOutput: 'false' },
      { input: 'n = 999983', expectedOutput: 'true', isHidden: true },
    ],
  },
  {
    title: 'Factorial',
    slug: 'factorial',
    description: 'Compute n! for small n. Return value as integer (assume n small enough to fit).',
    difficulty: 'EASY',
    topic: 'Math',
    examples: [{ input: 'n = 5', output: '120' }],
    constraints: ['0 <= n <= 20'],
    sampleInput: 'n = 5',
    sampleOutput: '120',
    testCases: [
      { input: 'n = 5', expectedOutput: '120' },
      { input: 'n = 0', expectedOutput: '1' },
      { input: 'n = 20', expectedOutput: '2432902008176640000', isHidden: true },
    ],
  },
  {
    title: 'Sum of Digits',
    slug: 'sum-of-digits',
    description: 'Return the sum of the decimal digits of an integer (handle negatives by sign).',
    difficulty: 'EASY',
    topic: 'Math',
    examples: [{ input: 'n = 1234', output: '10' }],
    constraints: ['-10^18 <= n <= 10^18'],
    sampleInput: 'n = 1234',
    sampleOutput: '10',
    testCases: [
      { input: 'n = 1234', expectedOutput: '10' },
      { input: 'n = -56', expectedOutput: '11' },
      { input: 'n = 1000000000000000000', expectedOutput: '1', isHidden: true },
    ],
  },
  {
    title: 'Fibonacci Number',
    slug: 'fibonacci-number',
    description: 'Return the nth Fibonacci number (0-indexed) using an efficient iterative method.',
    difficulty: 'EASY',
    topic: 'Math',
    examples: [{ input: 'n = 5', output: '5' }],
    constraints: ['0 <= n <= 45'],
    sampleInput: 'n = 5',
    sampleOutput: '5',
    testCases: [
      { input: 'n = 0', expectedOutput: '0' },
      { input: 'n = 1', expectedOutput: '1' },
      { input: 'n = 45', expectedOutput: '1134903170', isHidden: true },
    ],
  },
  // MEDIUM (10)
  {
    title: 'Pow(x,n)',
    slug: 'powx-n',
    description: 'Implement pow(x, n) (x raised to the power n) efficiently (fast exponentiation).',
    difficulty: 'MEDIUM',
    topic: 'Math',
    examples: [{ input: 'x = 2.00000, n = 10', output: '1024.00000' }],
    constraints: ['-100.0 <= x <= 100.0', '-2^31 <= n <= 2^31 - 1'],
    sampleInput: 'x = 2.00000, n = 10',
    sampleOutput: '1024.00000',
    testCases: [
      { input: 'x = 2.0, n = 10', expectedOutput: '1024.00000' },
      { input: 'x = 2.1, n = 3', expectedOutput: '9.26100' },
      { input: 'x = 2.0, n = -2', expectedOutput: '0.25000', isHidden: true },
    ],
  },
  {
    title: 'Happy Number',
    slug: 'happy-number',
    description: 'Determine whether a number is a happy number using cycle detection.',
    difficulty: 'MEDIUM',
    topic: 'Math',
    examples: [{ input: 'n = 19', output: 'true' }],
    constraints: ['1 <= n <= 10^9'],
    sampleInput: 'n = 19',
    sampleOutput: 'true',
    testCases: [
      { input: 'n = 19', expectedOutput: 'true' },
      { input: 'n = 2', expectedOutput: 'false' },
      { input: 'n = 7', expectedOutput: 'true', isHidden: true },
    ],
  },
  {
    title: 'Integer Break',
    slug: 'integer-break',
    description: 'Break integer n into sum of at least two positive integers to maximize product.',
    difficulty: 'MEDIUM',
    topic: 'Math',
    examples: [{ input: 'n = 10', output: '36' }],
    constraints: ['2 <= n <= 58'],
    sampleInput: 'n = 10',
    sampleOutput: '36',
    testCases: [
      { input: 'n = 2', expectedOutput: '1' },
      { input: 'n = 10', expectedOutput: '36' },
      { input: 'n = 58', expectedOutput: '...', isHidden: true },
    ],
  },
  {
    title: 'Fraction to Recurring Decimal',
    slug: 'fraction-to-recurring-decimal',
    description:
      'Given numerator and denominator, return decimal representation with recurring part in parentheses.',
    difficulty: 'MEDIUM',
    topic: 'Math',
    examples: [{ input: 'numerator = 1, denominator = 3', output: '0.(3)' }],
    constraints: ['-2^31 <= numerator, denominator <= 2^31 - 1', 'denominator != 0'],
    sampleInput: 'numerator = 1, denominator = 3',
    sampleOutput: '0.(3)',
    testCases: [
      { input: 'numerator = 1, denominator = 2', expectedOutput: '0.5' },
      { input: 'numerator = 2, denominator = 3', expectedOutput: '0.(6)' },
      { input: 'numerator = -50, denominator = 8', expectedOutput: '-6.25', isHidden: true },
    ],
  },
  {
    title: 'Count Primes',
    slug: 'count-primes',
    description: 'Return the number of prime numbers less than a non-negative integer n.',
    difficulty: 'MEDIUM',
    topic: 'Math',
    examples: [{ input: 'n = 10', output: '4' }],
    constraints: ['0 <= n <= 10^6'],
    sampleInput: 'n = 10',
    sampleOutput: '4',
    testCases: [
      { input: 'n = 10', expectedOutput: '4' },
      { input: 'n = 0', expectedOutput: '0' },
      { input: 'n = 1000000', expectedOutput: '78498', isHidden: true },
    ],
  },
  {
    title: 'Ugly Number II',
    slug: 'ugly-number-ii',
    description:
      'Find the nth ugly number where ugly numbers are positive numbers whose prime factors are limited to 2, 3, 5.',
    difficulty: 'MEDIUM',
    topic: 'Math',
    examples: [{ input: 'n = 10', output: '12' }],
    constraints: ['1 <= n <= 1690'],
    sampleInput: 'n = 10',
    sampleOutput: '12',
    testCases: [
      { input: 'n = 1', expectedOutput: '1' },
      { input: 'n = 10', expectedOutput: '12' },
      { input: 'n = 1690', expectedOutput: '2123366400', isHidden: true },
    ],
  },
  {
    title: 'Excel Column Number',
    slug: 'excel-column-number',
    description: 'Convert a column title as appear in Excel to its corresponding column number.',
    difficulty: 'MEDIUM',
    topic: 'Math',
    examples: [{ input: 'columnTitle = "AB"', output: '28' }],
    constraints: ['1 <= columnTitle.length <= 7', 'columnTitle contains uppercase letters'],
    sampleInput: 'columnTitle = "AB"',
    sampleOutput: '28',
    testCases: [
      { input: 'columnTitle = "A"', expectedOutput: '1' },
      { input: 'columnTitle = "AB"', expectedOutput: '28' },
      { input: 'columnTitle = "FXSHRXW"', expectedOutput: '2147483647', isHidden: true },
    ],
  },
  {
    title: 'Product of Array Except Self',
    slug: 'product-of-array-except-self-math',
    description:
      'Return an array output where output[i] is the product of all the elements of nums except nums[i].',
    difficulty: 'MEDIUM',
    topic: 'Math',
    examples: [{ input: 'nums = [1,2,3,4]', output: '[24,12,8,6]' }],
    constraints: ['2 <= nums.length <= 10^5', '-30 <= nums[i] <= 30'],
    sampleInput: 'nums = [1,2,3,4]',
    sampleOutput: '[24,12,8,6]',
    testCases: [
      { input: 'nums = [1,2,3,4]', expectedOutput: '[24,12,8,6]' },
      { input: 'nums = [-1,1,0,-3,3]', expectedOutput: '[0,0,9,0,0]' },
      { input: 'nums = [2,3,4,5]', expectedOutput: '[120,60,30,24]', isHidden: true },
    ],
  },
  {
    title: 'Sieve of Eratosthenes',
    slug: 'sieve-of-eratosthenes',
    description: 'Given n, return list of primes less than or equal to n using sieve.',
    difficulty: 'MEDIUM',
    topic: 'Math',
    examples: [{ input: 'n = 10', output: '[2,3,5,7]' }],
    constraints: ['0 <= n <= 10^6'],
    sampleInput: 'n = 10',
    sampleOutput: '[2,3,5,7]',
    testCases: [
      { input: 'n = 10', expectedOutput: '[2,3,5,7]' },
      { input: 'n = 2', expectedOutput: '[2]' },
      { input: 'n = 100', expectedOutput: '...', isHidden: true },
    ],
  },
  {
    title: 'Modular Arithmetic Problem',
    slug: 'modular-arithmetic-problem',
    description:
      'Compute (a^b) mod m efficiently for given integers using fast exponentiation under modulus.',
    difficulty: 'MEDIUM',
    topic: 'Math',
    examples: [{ input: 'a = 2, b = 10, m = 1000', output: '24' }],
    constraints: ['1 <= a, b, m <= 10^9'],
    sampleInput: 'a = 2, b = 10, m = 1000',
    sampleOutput: '24',
    testCases: [
      { input: 'a = 2, b = 10, m = 1000', expectedOutput: '24' },
      { input: 'a = 3, b = 100, m = 50', expectedOutput: '1' },
      { input: 'a = 10, b = 1000000000, m = 1000000007', expectedOutput: '...', isHidden: true },
    ],
  },
  // HARD (5)
  {
    title: 'Nth Magical Number',
    slug: 'nth-magical-number',
    description:
      'Find the nth magical number divisible by either a or b under modulo 10^9+7 using number theory.',
    difficulty: 'HARD',
    topic: 'Math',
    examples: [{ input: 'n = 1, a = 2, b = 3', output: '2' }],
    constraints: ['1 <= n <= 10^9', '1 <= a, b <= 10^9'],
    sampleInput: 'n = 1, a = 2, b = 3',
    sampleOutput: '2',
    testCases: [
      { input: 'n = 1, a = 2, b = 3', expectedOutput: '2' },
      { input: 'n = 4, a = 2, b = 3', expectedOutput: '6' },
      { input: 'n = 1000000000, a = 40000, b = 40001', expectedOutput: '...', isHidden: true },
    ],
  },
  {
    title: 'Super Pow',
    slug: 'super-pow',
    description:
      'Compute a^b where b is given as a large array of digits; use modular exponentiation with Euler/Totient tricks.',
    difficulty: 'HARD',
    topic: 'Math',
    examples: [{ input: 'a = 2, b = [3]', output: '8' }],
    constraints: ['1 <= a <= 10^9', '1 <= b.length <= 10^4'],
    sampleInput: 'a = 2, b = [3]',
    sampleOutput: '8',
    testCases: [
      { input: 'a = 2, b = [3]', expectedOutput: '8' },
      { input: 'a = 2, b = [1,0]', expectedOutput: '1024', isHidden: true },
    ],
  },
  {
    title: 'Hard Number Theory Problem',
    slug: 'hard-number-theory-problem',
    description:
      'Advanced number theory: compute a specialized multiplicative function over a range efficiently.',
    difficulty: 'HARD',
    topic: 'Math',
    examples: [{ input: 'n = 10', output: '42' }],
    constraints: ['1 <= n <= 10^7'],
    sampleInput: 'n = 10',
    sampleOutput: '42',
    testCases: [
      { input: 'n = 10', expectedOutput: '42' },
      { input: 'n = 1000', expectedOutput: '...', isHidden: true },
    ],
  },
  {
    title: 'Advanced Modular Arithmetic',
    slug: 'advanced-modular-arithmetic',
    description:
      'Solve modular linear equations and systems efficiently with Chinese remainder theorem and inverses.',
    difficulty: 'HARD',
    topic: 'Math',
    examples: [{ input: 'equations = [[2,3,1],[3,5,2]]', output: 'x = 11' }],
    constraints: ['1 <= number of equations <= 10', 'moduli are pairwise coprime'],
    sampleInput: 'equations = [[2,3,1],[3,5,2]]',
    sampleOutput: 'x = 11',
    testCases: [
      { input: 'equations = [[2,3,1]]', expectedOutput: 'x = 1' },
      { input: 'equations = [[2,3,1],[3,5,2]]', expectedOutput: 'x = 11', isHidden: true },
    ],
  },
  {
    title: 'Mathematical Optimization Problem',
    slug: 'mathematical-optimization-problem',
    description:
      'Given constraints and an objective defined over integers, compute the optimal integer solution using number-theoretic optimization techniques.',
    difficulty: 'HARD',
    topic: 'Math',
    examples: [{ input: 'params = [[1,2,3]]', output: '42' }],
    constraints: ['Problem-specific; small input sizes for exact algorithms'],
    sampleInput: 'params = [[1,2,3]]',
    sampleOutput: '42',
    testCases: [
      { input: 'params = [[1,2,3]]', expectedOutput: '42' },
      { input: 'params = [[5,5,5]]', expectedOutput: '...', isHidden: true },
    ],
  },
];
